In [1]:
import torch
from utils import load_checkpoint

/Users/vdine/miniconda3/envs/ffcv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
if torch.cuda.is_available():
    torch.cuda.set_device(int(args.gpu))
    device = torch.device(f"cuda:{int(args.gpu)}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

In [4]:
save_path = "results/cifar10"
pruning = 0

In [15]:
torch.load(save_path + "/0model_SA_best.pth.tar")

/var/folders/17/d5wm_d6x5zv68h4w18r3246h4xmqkj/T/ipykernel_23791/963741759.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(save_path + "/0model_SA_best.pth.ta

{'state': 0,
 'result': {'train_ta': [33.96222222222222,
   54.76444444444444,
   65.67555555555556,
   73.0911111111111,
   76.91777777777777,
   79.67111111111112,
   81.69777777777777,
   83.36444444444444,
   84.7311111111111,
   85.54],
  'test_ta': [46.18888888888889,
   59.44444444444444,
   67.32222222222222,
   71.8,
   72.87777777777778,
   75.07777777777778,
   74.4888888888889,
   78.26666666666667,
   79.41111111111111,
   79.33333333333333],
  'val_ta': [44.859999926757816,
   58.73999996337891,
   64.59999989013671,
   72.63999990234375,
   74.07999992675781,
   74.61999993896484,
   76.4,
   78.19999991455079,
   77.41999987792968,
   79.08000003662109]},
 'epoch': 10,
 'state_dict': OrderedDict([('normalize.mean',
               tensor([0.4914, 0.4822, 0.4465], device='mps:0')),
              ('normalize.std',
               tensor([0.2470, 0.2435, 0.2616], device='mps:0')),
              ('conv1.weight',
               tensor([[[[-0.0828, -0.0486,  0.0137],
          

: 

In [16]:
results = load_checkpoint(device, save_path, pruning, filename="checkpoint.pth.tar")
results.keys()

Load checkpoint from:results/cifar10/0checkpoint.pth.tar


dict_keys(['state', 'result', 'epoch', 'state_dict', 'best_sa', 'optimizer', 'scheduler', 'init_weight'])

: 

In [17]:
results['result']

{'train_ta': [33.96222222222222,
  54.76444444444444,
  65.67555555555556,
  73.0911111111111,
  76.91777777777777,
  79.67111111111112,
  81.69777777777777,
  83.36444444444444,
  84.7311111111111,
  85.54],
 'test_ta': [46.18888888888889,
  59.44444444444444,
  67.32222222222222,
  71.8,
  72.87777777777778,
  75.07777777777778,
  74.4888888888889,
  78.26666666666667,
  79.41111111111111,
  79.33333333333333],
 'val_ta': [44.859999926757816,
  58.73999996337891,
  64.59999989013671,
  72.63999990234375,
  74.07999992675781,
  74.61999993896484,
  76.4,
  78.19999991455079,
  77.41999987792968,
  79.08000003662109]}

: 

In [18]:
torch.load(save_path + "/mask_SRLeval_result.pth.tar", weights_only=False)

{'accuracy': {'retain': 85.42222221996165,
  'forget': 0.13333333333333333,
  'val': 74.8999999633789,
  'test': 83.71111111111111},
 'SVC_MIA_forget_efficacy': {'correctness': 0.9986666666666667,
  'confidence': 1.0,
  'entropy': 0.8546666666666667,
  'm_entropy': 0.8186666666666667,
  'prob': 0.4535555555555556},
 'SVC_MIA_training_privacy': {'correctness': 0.5069305555555556,
  'confidence': 0.5125972222222221,
  'entropy': 0.5106527777777778,
  'm_entropy': 0.5094583333333333,
  'prob': 0.4995555555555556}}

: 

In [19]:
torch.load(save_path + "/SRLeval_result.pth.tar", weights_only=False)

{'accuracy': {'retain': 87.05679012119623,
  'forget': 0.08888888888888889,
  'val': 76.78,
  'test': 84.9888888888889},
 'SVC_MIA_forget_efficacy': {'correctness': 0.9991111111111111,
  'confidence': 1.0,
  'entropy': 0.8568888888888889,
  'm_entropy': 0.8446666666666667,
  'prob': 0.7528888888888889},
 'SVC_MIA_training_privacy': {'correctness': 0.5099583333333333,
  'confidence': 0.5173611111111112,
  'entropy': 0.5103611111111112,
  'm_entropy': 0.5106111111111111,
  'prob': 0.5004166666666666}}

: 

In [20]:
torch.load(save_path + "/SalUneval_result.pth.tar", weights_only=False)

{'accuracy': {'retain': 86.28641974630473,
  'forget': 0.3111111111111111,
  'val': 75.74000002441406,
  'test': 84.32222222222222},
 'SVC_MIA_forget_efficacy': {'correctness': 0.9968888888888889,
  'confidence': 1.0,
  'entropy': 0.8566666666666667,
  'm_entropy': 0.8368888888888889,
  'prob': 0.6451111111111112},
 'SVC_MIA_training_privacy': {'correctness': 0.509625,
  'confidence': 0.5133611111111112,
  'entropy': 0.5164583333333334,
  'm_entropy': 0.5166666666666666,
  'prob': 0.5037777777777778}}

: 

In [21]:
torch.load(save_path + "/mix_SRLeval_result.pth.tar", weights_only=False)

{'accuracy': {'retain': 86.3703703681098,
  'forget': 0.5555555555555556,
  'val': 75.63999995117187,
  'test': 84.12222222222222},
 'SVC_MIA_forget_efficacy': {'correctness': 0.9944444444444445,
  'confidence': 1.0,
  'entropy': 0.8806666666666667,
  'm_entropy': 0.8531111111111112,
  'prob': 0.4528888888888889},
 'SVC_MIA_training_privacy': {'correctness': 0.510375,
  'confidence': 0.513125,
  'entropy': 0.5118888888888888,
  'm_entropy': 0.5115416666666667,
  'prob': 0.5025277777777777}}

: 

: 

: 